"""Initial migration

Revision ID: 9e9b534b8836
Revises: 
Create Date: 2026-08-28 12:01:52.693523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '9e9b534b8836'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
