"""multi-tenant auth: merchants, users, refresh tokens, tenant scoping

Revision ID: f57f860407d5
Revises: 9e9b534b8836
Create Date: 2026-08-28 21:39:51.249553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f57f860407d5'
down_revision: Union[str, None] = '9e9b534b8836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('razorpay_key_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('daily_recovery_cap', sa.Integer(), nullable=False),
    sa.Column('max_auto_recovery_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_index(op.f('ix_merchants_slug'), 'merchants', ['slug'], unique=True)
    op.create_table('webhook_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'provider')
    )
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.Enum('FAILURE_DETECTED', 'AI_DIAGNOSIS', 'POLICY_DECISION', 'EXECUTION_STARTED', 'EXECUTION_SUCCEEDED', 'EXECUTION_FAILED', 'ESCALATED_TO_REVIEW', 'REVIEW_APPROVED', 'REVIEW_REJECTED', 'WEBHOOK_RECEIVED', 'RECOVERY_RECONCILED', 'STOPPING_RULE_TRIGGERED', name='audit_event_type'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_customer_id'), 'audit_log', ['customer_id'], unique=False)
    op.create_index(op.f('ix_audit_log_merchant_id'), 'audit_log', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_audit_log_payment_id'), 'audit_log', ['payment_id'], unique=False)
    op.create_index('ix_audit_merchant_created', 'audit_log', ['merchant_id', 'created_at'], unique=False)
    op.create_index('ix_audit_merchant_payment', 'audit_log', ['merchant_id', 'payment_id'], unique=False)
    op.create_table('executions',
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'STARTED', 'SUCCEEDED', 'FAILED', 'UNKNOWN', name='execution_status'), nullable=False),
    sa.Column('external_reference', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('initiated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index(op.f('ix_executions_customer_id'), 'executions', ['customer_id'], unique=False)
    op.create_index('ix_executions_merchant_created', 'executions', ['merchant_id', 'created_at'], unique=False)
    op.create_index('ix_executions_merchant_customer_created', 'executions', ['merchant_id', 'customer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_executions_merchant_id'), 'executions', ['merchant_id'], unique=False)
    op.create_index('ix_executions_merchant_payment', 'executions', ['merchant_id', 'payment_id'], unique=False)
    op.create_index(op.f('ix_executions_payment_id'), 'executions', ['payment_id'], unique=False)
    op.create_table('pending_reviews',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('policy_reason', sa.String(), nullable=False),
    sa.Column('ai_diagnosis', sa.String(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='review_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_pending_reviews_customer_id'), 'pending_reviews', ['customer_id'], unique=False)
    op.create_index(op.f('ix_pending_reviews_merchant_id'), 'pending_reviews', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_pending_reviews_payment_id'), 'pending_reviews', ['payment_id'], unique=False)
    op.create_index('ix_reviews_merchant_status', 'pending_reviews', ['merchant_id', 'status'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('VIEWER', 'ANALYST', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_merchant_id'), 'users', ['merchant_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index('ix_refresh_tokens_family_active', 'refresh_tokens', ['family_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_family_active', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_merchant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_reviews_merchant_status', table_name='pending_reviews')
    op.drop_index(op.f('ix_pending_reviews_payment_id'), table_name='pending_reviews')
    op.drop_index(op.f('ix_pending_reviews_merchant_id'), table_name='pending_reviews')
    op.drop_index(op.f('ix_pending_reviews_customer_id'), table_name='pending_reviews')
    op.drop_table('pending_reviews')
    op.drop_index(op.f('ix_executions_payment_id'), table_name='executions')
    op.drop_index('ix_executions_merchant_payment', table_name='executions')
    op.drop_index(op.f('ix_executions_merchant_id'), table_name='executions')
    op.drop_index('ix_executions_merchant_customer_created', table_name='executions')
    op.drop_index('ix_executions_merchant_created', table_name='executions')
    op.drop_index(op.f('ix_executions_customer_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index('ix_audit_merchant_payment', table_name='audit_log')
    op.drop_index('ix_audit_merchant_created', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_payment_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_merchant_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_customer_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_merchants_slug'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
